server {
    listen 80;
    server_name _;

    # 算力调度
    location /slms/ {
        proxy_pass http://slms/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    # 算力纳管
    location /cps/ {
        proxy_pass http://cps/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # �[34m~I~M端 3�[34m~ZAI 大模�[34m~^~K广�[34m~\
     #location /hub/ {
     #    proxy_pass http://hub/;
     #    proxy_set_header Host $host;
     #    proxy_set_header X-Real-IP $remote_addr;
     #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     #}

    # �[34m~P~N端 API
    location /api/ {
        proxy_pass http://sldp-back:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}