"""update user table

Revision ID: 020771890a9b
Revises: 3e513490db92
Create Date: 2026-02-01 16:09:39.286166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020771890a9b'
down_revision: Union[str, Sequence[str], None] = '3e513490db92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ss_users', 'ss_roles', ['role_code'], ['role_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ss_users', type_='foreignkey')
    # ### end Alembic commands ###
