"""add member is_frozen

Revision ID: 2a05cc3f1952
Revises: 5c0e5367dc5f
Create Date: 2026-03-12 12:25:39.943031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a05cc3f1952'
down_revision: Union[str, Sequence[str], None] = '5c0e5367dc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ss_members', sa.Column('is_frozen', sa.Boolean(), nullable=False, comment='是否冻结'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ss_members', 'is_frozen')
    # ### end Alembic commands ###
