"""update_cer table

Revision ID: 380942a31775
Revises: 
Create Date: 2026-02-08 21:07:18.379016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380942a31775'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ss_roles',
    sa.Column('id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('role_code', sa.String(length=50), nullable=True, comment='角色编号'),
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code'),
    comment='角色表'
    )
    op.create_table('ss_users',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='登录用户名'),
    sa.Column('hashed_password', sa.String(length=200), nullable=True, comment='加密后的密码'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('role_code', sa.String(length=50), nullable=True, comment='权限Code（角色标识）'),
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='上级用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_ss_users_role_code'), 'ss_users', ['role_code'], unique=False)
    op.create_index(op.f('ix_ss_users_username'), 'ss_users', ['username'], unique=True)
    op.create_table('ss_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('refresh_token', sa.String(length=512), nullable=False, comment='刷新 token（hash 或原文）'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='刷新 token 到期时间'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='登录IP'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='客户端 UA'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['ss_users.id'], name='fk_ss_sessions_user_id'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户登录会话（refresh token 存储）；用于单点登录'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ss_sessions')
    op.drop_index(op.f('ix_ss_users_username'), table_name='ss_users')
    op.drop_index(op.f('ix_ss_users_role_code'), table_name='ss_users')
    op.drop_table('ss_users')
    op.drop_table('ss_roles')
    # ### end Alembic commands ###
