"""make member user nullable

Revision ID: 551054cdcd19
Revises: 2a05cc3f1952
Create Date: 2026-03-12 12:30:54.836794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '551054cdcd19'
down_revision: Union[str, Sequence[str], None] = '2a05cc3f1952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ss_members', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='用户ID(一对一)')
    op.alter_column('ss_members', 'member_account',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True,
               existing_comment='会员账号(用户账号)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ss_members', 'member_account',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False,
               existing_comment='会员账号(用户账号)')
    op.alter_column('ss_members', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='用户ID(一对一)')
    # ### end Alembic commands ###
