"""add member and user_type

Revision ID: 5c0e5367dc5f
Revises: 380942a31775
Create Date: 2026-03-12 11:12:02.327552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0e5367dc5f'
down_revision: Union[str, Sequence[str], None] = '380942a31775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ss_members',
    sa.Column('id', sa.Integer(), nullable=False, comment='会员ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID(一对一)'),
    sa.Column('member_name', sa.String(length=128), nullable=False, comment='会员名称/企业名称'),
    sa.Column('member_type', sa.String(length=20), nullable=False, comment='会员类型：PERSONAL/COMPANY'),
    sa.Column('credit_code', sa.String(length=64), nullable=True, comment='社会信用码(企业)'),
    sa.Column('contact_phone', sa.String(length=32), nullable=True, comment='联系电话'),
    sa.Column('contact_email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('industry', sa.String(length=64), nullable=True, comment='行业分类'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('member_person_name', sa.String(length=64), nullable=True, comment='会员姓名'),
    sa.Column('member_account', sa.String(length=64), nullable=False, comment='会员账号(用户账号)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间(UTC)'),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='会员表'
    )
    op.add_column('ss_users', sa.Column('user_type', sa.String(length=20), nullable=False, comment='用户类型：internal/tenant'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ss_users', 'user_type')
    op.drop_table('ss_members')
    # ### end Alembic commands ###
