"""create init_sso table

Revision ID: 74ec132e5156
Revises: 
Create Date: 2025-11-20 10:43:43.757149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ec132e5156'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ss_roles',
    sa.Column('id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('role_name', sa.String(length=50), nullable=True, comment='角色名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表'
    )
    op.create_index(op.f('ix_ss_roles_role_name'), 'ss_roles', ['role_name'], unique=True)
    op.create_table('ss_users',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='登录用户名'),
    sa.Column('hashed_password', sa.String(length=200), nullable=True, comment='加密后的密码'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('mobile', sa.String(length=20), nullable=True, comment='手机号码'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_ss_users_id'), 'ss_users', ['id'], unique=False)
    op.create_index(op.f('ix_ss_users_username'), 'ss_users', ['username'], unique=True)
    op.create_table('ss_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ss_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ss_users.id'], ),
    comment='用户角色关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ss_user_roles')
    op.drop_index(op.f('ix_ss_users_username'), table_name='ss_users')
    op.drop_index(op.f('ix_ss_users_id'), table_name='ss_users')
    op.drop_table('ss_users')
    op.drop_index(op.f('ix_ss_roles_role_name'), table_name='ss_roles')
    op.drop_table('ss_roles')
    # ### end Alembic commands ###
