"""update user table

Revision ID: b75c3d6d10aa
Revises: 020771890a9b
Create Date: 2026-02-01 16:35:30.027929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b75c3d6d10aa'
down_revision: Union[str, Sequence[str], None] = '020771890a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ss_users', 'parent_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='上级用户ID')
    op.drop_constraint(op.f('fk_users_parent_id'), 'ss_users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_users_parent_id'), 'ss_users', 'ss_users', ['parent_id'], ['id'])
    op.alter_column('ss_users', 'parent_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='上级用户ID')
    # ### end Alembic commands ###
