"""drop members

Revision ID: d9ceeba68a1b
Revises: 551054cdcd19
Create Date: 2026-03-13 17:57:18.554793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9ceeba68a1b'
down_revision: Union[str, Sequence[str], None] = '551054cdcd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_id'), table_name='ss_members')
    op.drop_table('ss_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ss_members',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='会员ID'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='用户ID(一对一)'),
    sa.Column('member_name', mysql.VARCHAR(length=128), nullable=False, comment='会员名称/企业名称'),
    sa.Column('member_type', mysql.VARCHAR(length=20), nullable=False, comment='会员类型：PERSONAL/COMPANY'),
    sa.Column('credit_code', mysql.VARCHAR(length=64), nullable=True, comment='社会信用码(企业)'),
    sa.Column('contact_phone', mysql.VARCHAR(length=32), nullable=True, comment='联系电话'),
    sa.Column('contact_email', mysql.VARCHAR(length=128), nullable=True, comment='邮箱'),
    sa.Column('industry', mysql.VARCHAR(length=64), nullable=True, comment='行业分类'),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True, comment='地址'),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.Column('member_person_name', mysql.VARCHAR(length=64), nullable=True, comment='会员姓名'),
    sa.Column('member_account', mysql.VARCHAR(length=64), nullable=True, comment='会员账号(用户账号)'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间(UTC)'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间(UTC)'),
    sa.Column('is_released', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('released_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_frozen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否冻结'),
    sa.PrimaryKeyConstraint('id'),
    comment='会员表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='会员表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('user_id'), 'ss_members', ['user_id'], unique=True)
    # ### end Alembic commands ###
