"""create user_session table

Revision ID: e01edf435039
Revises: 74ec132e5156
Create Date: 2025-11-20 13:15:13.747606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01edf435039'
down_revision: Union[str, Sequence[str], None] = '74ec132e5156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ss_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('refresh_token', sa.String(length=512), nullable=False, comment='刷新 token（hash 或原文）'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='刷新 token 到期时间'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='登录IP'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='客户端 UA'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['ss_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户登录会话（refresh token 存储）；用于单点登录'
    )
    op.create_index(op.f('ix_ss_sessions_id'), 'ss_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ss_sessions_user_id'), 'ss_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ss_sessions_user_id'), table_name='ss_sessions')
    op.drop_index(op.f('ix_ss_sessions_id'), table_name='ss_sessions')
    op.drop_table('ss_sessions')
    # ### end Alembic commands ###
