"""create vpc table

Revision ID: 776a2c4f7eee
Revises: cdc5dbe7fecb
Create Date: 2025-11-17 11:28:15.544587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776a2c4f7eee'
down_revision: Union[str, Sequence[str], None] = 'cdc5dbe7fecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cm_vpc',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('vpc_name', sa.String(length=100), nullable=False, comment='VPC 名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='VPC 描述信息'),
    sa.Column('resource_group_id', sa.Integer(), nullable=True, comment='资源组ID'),
    sa.Column('cloud_provider_code', sa.Integer(), nullable=False, comment='云厂商code'),
    sa.Column('cloud_certificate_id', sa.Integer(), nullable=False, comment='云凭证ID'),
    sa.Column('region_id', sa.String(length=100), nullable=False, comment='区域ID'),
    sa.Column('network_type', sa.String(length=20), nullable=False, comment='网络类型，例如 VPC/CLASSIC'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    comment='云厂商虚拟私有网络（VPC）信息表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cm_vpc')
    # ### end Alembic commands ###
