"""create dict_item table

Revision ID: cdc5dbe7fecb
Revises: 
Create Date: 2025-11-16 23:40:42.720384

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, String, column, Text, DateTime

# revision identifiers, used by Alembic.
revision: str = 'cdc5dbe7fecb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cm_dict_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('type_code', sa.String(length=50), nullable=False, comment='字典类型标识'),
        sa.Column('item_code', sa.String(length=50), nullable=False, comment='字典项编码'),
        sa.Column('item_name', sa.String(length=100), nullable=False, comment='字典项名称'),
        sa.Column('description', sa.Text(), nullable=True, comment='描述信息，可选'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
        sa.PrimaryKeyConstraint('id'),
        comment='通用字典表'
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cm_dict_item')
    # ### end Alembic commands ###
