"""init table

Revision ID: eacfb7562201
Revises: 
Create Date: 2026-02-07 21:15:30.436315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacfb7562201'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='分类名称'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='唯一标识'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='分类描述'),
    sa.Column('icon', sa.String(length=64), nullable=True, comment='分类图标'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    comment='模型分类表'
    )
    op.create_table('hub_models',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='模型ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='模型名称'),
    sa.Column('slug', sa.String(length=255), nullable=True, comment='模型唯一标识'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('author', sa.String(length=255), nullable=True, comment='作者'),
    sa.Column('downloads', sa.String(length=255), nullable=True, comment='下载次数'),
    sa.Column('likes', sa.String(length=255), nullable=True, comment='收藏次数'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('framework', sa.String(length=255), nullable=True, comment='标签'),
    sa.Column('license', sa.String(length=255), nullable=True, comment='标签'),
    sa.Column('model_size', sa.String(length=255), nullable=True, comment='模型大小'),
    sa.Column('language', sa.String(length=255), nullable=True, comment='语言'),
    sa.Column('category_slug', sa.String(length=255), nullable=True, comment='分类标识'),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='图标地址'),
    sa.Column('created_at', sa.String(length=255), nullable=True, comment='创建时间（UTC）'),
    sa.Column('update_at', sa.String(length=255), nullable=True, comment='创建时间（UTC）'),
    sa.Column('last_modified', sa.String(length=255), nullable=True, comment='最后修改时间'),
    sa.Column('published_date', sa.String(length=255), nullable=True, comment='最后修改时间'),
    sa.Column('readme', sa.Text(), nullable=True, comment='描述'),
    sa.Column('usage_example', sa.Text(), nullable=True, comment='描述'),
    sa.Column('paper_url', sa.String(length=255), nullable=True, comment='paper_url'),
    sa.Column('github_url', sa.String(length=255), nullable=True, comment='github_url'),
    sa.Column('model_files', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('task_type', sa.String(length=255), nullable=True, comment='标签'),
    sa.Column('domain', sa.String(length=255), nullable=True, comment='一些描述'),
    sa.Column('model_scope', sa.String(length=255), nullable=True, comment='一些描述'),
    sa.Column('limitations', sa.Text(), nullable=True, comment='一些描述'),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=True, comment='一些描述'),
    sa.Column('hardware_requirements', sa.Text(), nullable=True, comment='一些描述'),
    sa.Column('inference_speed', sa.Text(), nullable=True, comment='一些描述'),
    sa.Column('docker_deployment', sa.Text(), nullable=True, comment='一些描述'),
    sa.Column('model_evaluation', sa.Text(), nullable=True, comment='一些描述'),
    sa.PrimaryKeyConstraint('id'),
    comment='模型临时表（无约束，用于数据清洗）'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hub_models')
    op.drop_table('hub_categories')
    # ### end Alembic commands ###
