"""init hub table

Revision ID: f0403cb1ebe3
Revises: 
Create Date: 2026-02-08 01:06:58.620723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0403cb1ebe3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='分类名称'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='唯一标识'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='分类描述'),
    sa.Column('icon', sa.String(length=64), nullable=True, comment='分类图标'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    comment='模型分类表'
    )
    op.create_table('hub_models',
    sa.Column('id', sa.Integer(), nullable=False, comment='模型ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='模型名称'),
    sa.Column('slug', sa.String(length=255), nullable=True, comment='唯一标识'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('author', sa.String(length=255), nullable=True, comment='作者'),
    sa.Column('downloads', sa.Integer(), nullable=False, comment='下载次数'),
    sa.Column('likes', sa.Integer(), nullable=False, comment='点赞数'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('framework', sa.String(length=100), nullable=True, comment='框架'),
    sa.Column('license', sa.String(length=100), nullable=True, comment='许可证'),
    sa.Column('model_size', sa.String(length=50), nullable=True, comment='模型大小'),
    sa.Column('language', sa.String(length=100), nullable=True, comment='语言'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('readme', sa.Text(), nullable=True, comment='说明文档'),
    sa.Column('usage_example', sa.Text(), nullable=True, comment='使用示例'),
    sa.Column('paper_url', sa.String(length=512), nullable=True, comment='论文地址'),
    sa.Column('github_url', sa.String(length=512), nullable=True, comment='GitHub 地址'),
    sa.Column('model_files', sa.JSON(), nullable=True, comment='模型文件'),
    sa.Column('last_modified', sa.DateTime(), nullable=True, comment='最后修改时间'),
    sa.Column('task_type', sa.String(length=100), nullable=True, comment='任务类型'),
    sa.Column('domain', sa.String(length=100), nullable=True, comment='领域'),
    sa.Column('published_date', sa.Date(), nullable=True, comment='发布日期'),
    sa.Column('model_scope', sa.Text(), nullable=True, comment='适用范围'),
    sa.Column('limitations', sa.Text(), nullable=True, comment='限制说明'),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=True, comment='评估指标'),
    sa.Column('hardware_requirements', sa.Text(), nullable=True, comment='硬件要求'),
    sa.Column('inference_speed', sa.Text(), nullable=True, comment='推理速度'),
    sa.Column('docker_deployment', sa.Text(), nullable=True, comment='Docker 部署'),
    sa.Column('deployment_guide', sa.Text(), nullable=True, comment='部署指南'),
    sa.Column('model_evaluation', sa.Text(), nullable=True, comment='模型评估'),
    sa.PrimaryKeyConstraint('id'),
    comment='模型表（无约束，用于数据清洗）'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hub_models')
    op.drop_table('hub_categories')
    # ### end Alembic commands ###
