"""create audit_log table

Revision ID: 59684955ba45
Revises: 75708f958529
Create Date: 2025-11-12 21:46:29.702202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d778c6e99b'
down_revision: Union[str, Sequence[str], None] = '75708f958529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pu_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='操作用户ID'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='操作用户名'),
    sa.Column('module', sa.String(length=100), nullable=False, comment='操作模块，例如 cloud、asset、user'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作动作，例如 create、update、delete'),
    sa.Column('target_type', sa.String(length=100), nullable=True, comment='目标类型，例如 cloud_region、instance'),
    sa.Column('target_id', sa.String(length=100), nullable=True, comment='目标对象ID'),
    sa.Column('request_data', sa.Text(), nullable=True, comment='操作请求参数（JSON）'),
    sa.Column('description', sa.Text(), nullable=True, comment="操作描述，例如 '创建云实例'"),
    sa.Column('status', sa.String(length=20), nullable=False, comment='操作状态：success / failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='请求来源IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    comment='操作审计日志表'
    )
    op.create_index(op.f('ix_pu_audit_log_id'), 'pu_audit_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pu_audit_log_id'), table_name='pu_audit_log')
    op.drop_table('pu_audit_log')
    # ### end Alembic commands ###
