"""create cloud_zone table

Revision ID: 6ad310445be2
Revises: d9d778c6e99b
Create Date: 2025-11-13 00:31:24.360149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad310445be2'
down_revision: Union[str, Sequence[str], None] = 'd9d778c6e99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pu_cloud_zone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False, comment='云厂商编码，例如 aliyun'),
    sa.Column('region_id', sa.String(length=100), nullable=False, comment='所属区域的 region_id'),
    sa.Column('zone_id', sa.String(length=100), nullable=False, comment='可用区代号，例如 cn-hangzhou-a'),
    sa.Column('zone_name', sa.String(length=200), nullable=False, comment='可用区名称，例如 华东1可用区A'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'region_id', 'zone_id', name='uq_provider_region_zone'),
    comment='云厂商可用区列表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pu_cloud_zone')
    # ### end Alembic commands ###
