"""create cloud_credentials_platform table

Revision ID: 8bf29e4706fc
Revises: 
Create Date: 2025-11-12 10:50:20.890552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf29e4706fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pu_cloud_credentials_platform',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False, comment='云厂商编码，例如 aliyun'),
    sa.Column('provider_name', sa.String(length=100), nullable=False, comment='云厂商名称'),
    sa.Column('access_key_id', sa.String(length=200), nullable=False, comment='AccessKey ID'),
    sa.Column('access_key_secret', sa.String(length=200), nullable=False, comment='AccessKey Secret（加密存储）'),
    sa.Column('endpoint', sa.String(length=200), nullable=False, comment='默认 Endpoint，例如 ecs.aliyuncs.com'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code'),
    comment='云厂商凭证与接入配置表'
    )
    op.create_index(op.f('ix_pu_cloud_credentials_platform_id'), 'pu_cloud_credentials_platform', ['id'], unique=False)
    op.create_table('pu_cloud_region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False, comment='云厂商编码，例如 aliyun'),
    sa.Column('region_id', sa.String(length=100), nullable=False, comment='地区代号（如 cn-hangzhou）'),
    sa.Column('region_name', sa.String(length=200), nullable=False, comment='地区名称（如 华东1（杭州））'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'region_id', name='uq_provider_region'),
    comment='云厂商区域列表'
    )
    op.create_index(op.f('ix_pu_cloud_region_id'), 'pu_cloud_region', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pu_cloud_region_id'), table_name='pu_cloud_region')
    op.drop_table('pu_cloud_region')
    op.drop_index(op.f('ix_pu_cloud_credentials_platform_id'), table_name='pu_cloud_credentials_platform')
    op.drop_table('pu_cloud_credentials_platform')
    # ### end Alembic commands ###
