"""create cloud_certificate table

Revision ID: ac5730ab836b
Revises: 6ad310445be2
Create Date: 2025-11-13 10:20:00.921951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5730ab836b'
down_revision: Union[str, Sequence[str], None] = '6ad310445be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pu_cloud_certificate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cloud_code', sa.String(length=50), nullable=False, comment='云凭证编码，例如 aliyun'),
    sa.Column('cloud_name', sa.String(length=100), nullable=False, comment='云凭证名称'),
    sa.Column('cloud_access_key_id', sa.String(length=200), nullable=False, comment='AccessKey ID'),
    sa.Column('cloud_access_key_secret', sa.String(length=200), nullable=False, comment='AccessKey Secret（加密存储）'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_code'),
    comment='用户云厂商的云凭证'
    )
    op.create_index(op.f('ix_pu_cloud_certificate_id'), 'pu_cloud_certificate', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pu_cloud_certificate_id'), table_name='pu_cloud_certificate')
    op.drop_table('pu_cloud_certificate')
    # ### end Alembic commands ###
