"""create resource_group table

Revision ID: d549aacbd93f
Revises: ac5730ab836b
Create Date: 2025-11-17 11:44:14.832978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd549aacbd93f'
down_revision: Union[str, Sequence[str], None] = 'ac5730ab836b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pu_resource_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='资源组名称（阿里云的 DisplayName）'),
    sa.Column('code', sa.String(length=100), nullable=True, comment='系统内部资源组编码，可选'),
    sa.Column('cloud_provider_code', sa.String(length=50), nullable=True, comment='云厂商编码，例如 aliyun'),
    sa.Column('cloud_resource_group_id', sa.String(length=200), nullable=True, comment='云厂商的资源组ID，例如 rg-acfmx1234****'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_provider_code', 'cloud_resource_group_id', name='uq_cloud_rg'),
    comment='资源组信息表'
    )
    op.create_index(op.f('ix_pu_resource_group_id'), 'pu_resource_group', ['id'], unique=False)
    op.create_table('pu_resource_group_binding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_group_id', sa.Integer(), nullable=False, comment='资源组 ID'),
    sa.Column('cloud_provider_code', sa.String(length=50), nullable=True, comment='云厂商，如 aliyun'),
    sa.Column('resource_type', sa.String(length=100), nullable=False, comment='资源类型，例如 ecs/vpc/bucket/subsystem_xxx'),
    sa.Column('resource_id', sa.String(length=200), nullable=False, comment='资源在系统内的唯一 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='绑定时间 (UTC)'),
    sa.ForeignKeyConstraint(['resource_group_id'], ['pu_resource_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_provider_code', 'resource_type', 'resource_id', name='uq_rg_resource'),
    comment='资源与资源组的绑定表'
    )
    op.create_index(op.f('ix_pu_resource_group_binding_id'), 'pu_resource_group_binding', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pu_resource_group_binding_id'), table_name='pu_resource_group_binding')
    op.drop_table('pu_resource_group_binding')
    op.drop_index(op.f('ix_pu_resource_group_id'), table_name='pu_resource_group')
    op.drop_table('pu_resource_group')
    # ### end Alembic commands ###
